#!/usr/bin/env python3

"""
Agregar nodos de arepacoin manualmente obteniendo la información desde el explorador de bloques
Manually add arepacoin nodes to daemon
(python 3.x)
"""
import json
import requests

from config import *

try:
    # Get las 24 hours nodes from blockchain explorer
    data = requests.get(URL_EXPLORER)
    if data.status_code == 200: # OK
        with open("./addnodes.sh", "w") as text_file:
            text_file.write(f"#!/bin/bash\n# This file is autogenerated by print_active_nodes.py\n")
            for i in json.loads(data.text)[0]['nodes']:
                print(f"Node: {i}")
                text_file.write(f"echo Adding node {i}\n")
                if not DATADIR:
                    text_file.write(f"{DAEMON_PATH} addnode {i} add\n")
                else:
                    text_file.write(f"{DAEMON_PATH} --datadir={DATADIR} addnode {i} add\n")
        print("\nPlease run addnodes.sh to add nodes to arepacoin daemon.")
    else:
        print(f"Arepacoin Blockchain Explorer not responding ( {URL_EXPLORER} )")

except:
    print(f"ERROR: No connection for {URL_EXPLORER} ")
